command_bus:
    logging: ~

services:
    _defaults:
        autowire: true
        public: true

    # User
    MsgPhp\User\Command\Handler\ChangeUserEmailHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\ChangeUserEmailCommand }]
    MsgPhp\User\Command\Handler\ChangeUserPasswordHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\ChangeUserPasswordCommand }]
    MsgPhp\User\Command\Handler\CreateUserHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\CreateUserCommand }]
    MsgPhp\User\Command\Handler\DeleteUserHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\DeleteUserCommand }]
    MsgPhp\User\Command\Handler\DisableUserHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\DisableUserCommand }]
    MsgPhp\User\Command\Handler\EnableUserHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\EnableUserCommand }]
    MsgPhp\User\Command\Handler\RequestUserPasswordHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\RequestUserPasswordCommand }]
    MsgPhp\User\Command\Handler\ResetUserPasswordHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\ResetUserPasswordCommand }]

    # User roles
    MsgPhp\User\Command\Handler\AddUserRoleHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\AddUserRoleCommand }]
    MsgPhp\User\Command\Handler\DeleteUserRoleHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\DeleteUserRoleCommand }]

    # Pending user
    MsgPhp\User\Command\Handler\ConfirmPendingUserHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\ConfirmPendingUserCommand }]
    MsgPhp\User\Command\Handler\CreatePendingUserHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\CreatePendingUserCommand }]

    # User secondary e-mail
    MsgPhp\User\Command\Handler\AddUserSecondaryEmailHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\AddUserSecondaryEmailCommand }]
    MsgPhp\User\Command\Handler\ConfirmUserSecondaryEmailHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\ConfirmUserSecondaryEmailCommand }]
    MsgPhp\User\Command\Handler\DeleteUserSecondaryEmailHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\DeleteUserSecondaryEmailCommand }]
    MsgPhp\User\Command\Handler\MarkUserSecondaryEmailPrimaryHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\MarkUserSecondaryEmailPrimaryCommand }]
    MsgPhp\User\Command\Handler\SetUserPendingPrimaryEmailHandler:
        tags: [{ name: command_handler, handles: MsgPhp\User\Command\SetUserPendingPrimaryEmailCommand }]
