event_bus:
    logging: ~

services:
    _defaults:
        autowire: true
        public: true

    App\EventSubscriber\SendAccountConfirmationUrlToPendingUser:
        tags: [{ name: event_subscriber, subscribes_to: MsgPhp\User\Event\PendingUserCreatedEvent }]
    App\EventSubscriber\SendEmailConfirmationUrlToUser:
        tags:
            - { name: event_subscriber, subscribes_to: MsgPhp\User\Event\UserSecondaryEmailAddedEvent }
            - { name: event_subscriber, subscribes_to: MsgPhp\User\Event\UserPendingPrimaryEmailCreatedEvent }
    App\EventSubscriber\SendPasswordResetUrlToUser:
        tags: [{ name: event_subscriber, subscribes_to: MsgPhp\User\Event\UserPasswordRequestedEvent }]
