login:
    path: /login
    controller: App\Controller\User\LoginController

logout:
    path: /logout

register:
    path: /register
    controller: App\Controller\User\RegisterController

confirm_account:
    path: /confirm-account/{token}
    controller: App\Controller\User\ConfirmAccountController

confirm_email:
    path: /confirm-email/{token}
    controller: App\Controller\User\ConfirmEmailController

forgot_password:
    path: /forgot-password
    controller: App\Controller\User\ForgotPasswordController

reset_password:
    path: /reset-password/{token}
    controller: App\Controller\User\ResetPasswordController

my_account:
    path: /my-account
    controller: App\Controller\User\MyAccountController
